src/main/java/com/realdolmen/thomasmore/controller/IndexController.java
package com.realdolmen.thomasmore.controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by JUZAU33 on 28/09/2017.
 */
@ManagedBean
@SessionScoped
public class IndexController {

    public String getHelloWorld() {
        return "Hello, world!";
    }
    public ArrayList<Integer> NummerTest() {
        ArrayList<Integer> nummers = new ArrayList<Integer>();
        for (int i = 0; i <= 10; i++) {
            nummers.add(i);
        }
        return nummers;
    }
}

src/main/webapp/included/navbar/navBar.xhtml
<!-- In plaats van een html-tag te gebruiken, begin je het bestand met een <ui:composition>-tag.
  Hierin moeten ook de gewenste namespaces komen. -->

<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:b="http://bootsfaces.net/ui">
    <!-- Om de CSS van iets te veranderen moet je naar een eigen CSS verwijzen. CSS van Bootstrap komt op Facebook te staan.-->
    <h:outputStylesheet library="style" name="navBar.css"></h:outputStylesheet>
    <h:outputStylesheet name="style/navBar.css"></h:outputStylesheet>
    <b:navBar brand="Home" iconAwesome="home" brandHref="#{request.contextPath}/index.xhtml" inverse="true">
        <b:navbarLinks>
            <b:navLink value="Producten" outcome="/producten/productenlijst"/>
            <!--<b:navLink outcome="#/index">#{helloWorldController.helloWorld}</b:navLink>
            <b:navLink href="#"></b:navLink>
            <b:dropMenu value="Dropdown" >
                <b:navLink value="Action" href="#"></b:navLink>
                <b:navLink value="Another action" href="#"></b:navLink>
                <b:navLink value="Something else here" href="#"></b:navLink>
                <b:navLink></b:navLink>
                <b:navLink header="Nav header"></b:navLink>
                <b:navLink value="Separated link" href="#"></b:navLink>
                <<b:dropMenu value="Nested submenu" iconAwesome="birthday-cake" iconAlign="right">
                    <b:navLink value="You can nest menus" href="#"></b:navLink>
                    <b:dropMenu value="Nested sub-submenu">
                        <b:navLink value="... as deep as ..." href="#"></b:navLink>
                        <b:dropMenu value="Nested sub-sub-submenu">
                            <b:navLink value="... you want!" href="#"></b:navLink>
                        </b:dropMenu>
                    </b:dropMenu>

                </b:dropMenu>
                <b:navLink value="One more separated link" href="#"></b:navLink>
            </b:dropMenu>-->
            <b:navLink  value="Contact" outcome="/support/index"></b:navLink>
        </b:navbarLinks>
        <!--<form class="navbar-form navbar-left hidden-md hidden-sm hidden-xs" action="search">
            <div class="form-group">
                <input type="text" class="form-control"/>
            </div>
            <button type="submit" class="btn btn-default">Bevestig</button>
        </form>-->

        <!-- Following line is needed for TBS 3.0.1 (panel content overflow issue) -->
        <b:navbarLinks pull="right" >
            <b:navLink  value="Registreren" outcome="/user/register"></b:navLink>
            <b:navLink  value="Inloggen" outcome="/user/login"></b:navLink>
        </b:navbarLinks>

    </b:navBar>
</ui:composition>

src/main/webapp/included/navbar/navBarLoggedIn.xhtml
<!-- In plaats van een html-tag te gebruiken, begin je het bestand met een <ui:composition>-tag.
  Hierin moeten ook de gewense namespaces komen. -->

<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
        xmlns:b="http://bootsfaces.net/ui">
    <!-- Om de CSS van iets te veranderen moet je naar een eigen CSS verwijzen. CSS van Bootstrap komt op Facebook te staan.-->
    <h:outputStylesheet name="style/style.css"></h:outputStylesheet>
    <h:outputStylesheet name="style/navBar.css"></h:outputStylesheet>
    <b:navBar brand="Welkom, #{userController.huidigeKlant.voornaam}" brandHref="#{request.contextPath}/index.xhtml" inverse="true" iconAwesome="home">
        <b:navbarLinks>
            <b:navLink value="Producten" outcome="/producten/productenlijst"/>
           <!--<b:dropMenu value="Dropdown" iconAwesome="birthday-cake">
                <b:navLink value="Action" href="#"></b:navLink>
                <b:navLink value="Another action" href="#"></b:navLink>
                <b:navLink value="Something else here" href="#"></b:navLink>
                <b:navLink></b:navLink>
                <b:navLink header="Nav header"></b:navLink>
                <b:navLink value="Separated link" href="#"></b:navLink>
                <b:dropMenu value="Nested submenu" iconAwesome="birthday-cake" iconAlign="right">
                    <b:navLink value="You can nest menus" href="#"></b:navLink>
                    <b:dropMenu value="Nested sub-submenu">
                        <b:navLink value="... as deep as ..." href="#"></b:navLink>
                        <b:dropMenu value="Nested sub-sub-submenu">
                            <b:navLink value="... you want!" href="#"></b:navLink>
                        </b:dropMenu>
                    </b:dropMenu>

                </b:dropMenu>
                <b:navLink value="One more separated link" href="#"></b:navLink>
            </b:dropMenu>-->
            <b:navLink  value="Contact" outcome="/support/index"></b:navLink>
            <b:navLink value="Support Ticket" outcome="#{supportTicketController.naarSupportTicket(session)}" ></b:navLink>
        </b:navbarLinks>
        <!--<form class="navbar-form navbar-left hidden-md hidden-sm hidden-xs" action="search">
            <div class="form-group">
                <input type="text" class="form-control"/>
            </div>
            <button type="submit" class="btn btn-default">Bevestig</button>
        </form>-->
        <!-- Following line is needed for TBS 3.0.1 (panel content overflow issue) -->
        <h:form>
            <b:navbarLinks pull="right">
                <b:navLink outcome="#{productController.naarWinkelkarretjeOverzicht(session)}" iconAwesome="shopping-basket"></b:navLink>
                <b:navLink value="Profiel" outcome="/user/my-account/dashboard"/>
                <b:navCommandLink value="Admin"  rendered="#{userController.sessionUserLevel == 3}" outcome="/admin/adminMain.xhtml"/>
                <b:navCommandLink value='Log uit' action="#{userController.logoutUser(session)}"/>
            </b:navbarLinks>
        </h:form>
    </b:navBar>
</ui:composition>